name: federated
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - argon2-cffi=20.1.0=py37h7b6447c_1
  - astroid=2.4.2=py37_0
  - async_generator=1.10=py37h28b3542_0
  - backcall=0.2.0=py_0
  - bleach=3.2.1=py_0
  - ca-certificates=2020.10.14=0
  - certifi=2020.6.20=pyhd3eb1b0_3
  - cffi=1.14.3=py37he30daa8_0
  - dbus=1.13.18=hb2f20db_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37_0
  - expat=2.2.10=he6710b0_2
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.10.4=h5ab3b9f_0
  - glib=2.66.1=h92f7085_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb31296c_0
  - icu=58.2=he6710b0_3
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - ipykernel=5.3.4=py37h5ca1d4c_0
  - ipython=7.19.0=py37hb070fc8_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.5.1=py_1
  - isort=5.6.4=py_0
  - jedi=0.17.2=py37_0
  - jinja2=2.11.2=py_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.2.0=py_2
  - jupyter=1.0.0=py37_7
  - jupyter_client=6.1.7=py_0
  - jupyter_console=6.2.0=py_0
  - jupyter_core=4.6.3=py37_0
  - jupyterlab_pygments=0.1.2=py_0
  - lazy-object-proxy=1.4.3=py37h7b6447c_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - markupsafe=1.1.1=py37h14c3975_1
  - mccabe=0.6.1=py37_1
  - mistune=0.8.4=py37h14c3975_1001
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py37_0
  - nbformat=5.0.8=py_0
  - ncurses=6.2=he6710b0_1
  - notebook=6.1.4=py37_0
  - openssl=1.1.1h=h7b6447c_0
  - packaging=20.4=py_0
  - pandoc=2.11=hb0f4dca_0
  - pandocfilters=1.4.3=py37h06a4308_1
  - parso=0.7.0=py_0
  - pcre=8.44=he6710b0_0
  - pexpect=4.8.0=py37_1
  - pickleshare=0.7.5=py37_1001
  - pip=20.2.4=py37h06a4308_0
  - prometheus_client=0.8.0=py_0
  - prompt-toolkit=3.0.8=py_0
  - prompt_toolkit=3.0.8=0
  - ptyprocess=0.6.0=py37_0
  - pycparser=2.20=py_2
  - pygments=2.7.2=pyhd3eb1b0_0
  - pylint=2.6.0=py37_0
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - pyrsistent=0.17.3=py37h7b6447c_0
  - python=3.7.9=h7579374_0
  - python-dateutil=2.8.1=py_0
  - pyzmq=19.0.2=py37he6710b0_1
  - qt=5.9.7=h5867ecd_1
  - qtconsole=4.7.7=py_0
  - qtpy=1.9.0=py_0
  - readline=8.0=h7b6447c_0
  - send2trash=1.5.0=py37_0
  - setuptools=50.3.1=py37h06a4308_1
  - sip=4.19.8=py37hf484d3e_0
  - six=1.15.0=py_0
  - sqlite=3.33.0=h62c20be_0
  - terminado=0.9.1=py37_0
  - testpath=0.4.4=py_0
  - tk=8.6.10=hbc83047_0
  - toml=0.10.1=py_0
  - tornado=6.0.4=py37h7b6447c_1
  - traitlets=5.0.5=py_0
  - typed-ast=1.4.1=py37h7b6447c_0
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py37_1
  - wheel=0.35.1=py_0
  - widgetsnbextension=3.5.1=py37_0
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.3=he6710b0_3
  - zipp=3.4.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.9.0
    - altgraph==0.17
    - astunparse==1.6.3
    - attrs==19.3.0
    - cachetools==3.1.1
    - chardet==3.0.4
    - cycler==0.10.0
    - dm-tree==0.1.5
    - flatbuffers==1.12
    - gast==0.3.3
    - google-auth==1.23.0
    - google-auth-oauthlib==0.4.2
    - google-pasta==0.2.0
    - grpcio==1.29.0
    - h5py==2.10.0
    - idna==2.10
    - keras==2.4.3
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.1
    - markdown==3.3.3
    - matplotlib==3.3.3
    - mpmath==1.1.0
    - nest-asyncio==1.4.3
    - numpy==1.18.5
    - oauthlib==3.1.0
    - opt-einsum==3.3.0
    - pillow==8.0.1
    - portpicker==1.3.1
    - protobuf==3.13.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyinstaller==4.1.dev0
    - pyinstaller-hooks-contrib==2020.10
    - pyyaml==5.3.1
    - requests==2.25.0
    - requests-oauthlib==1.3.0
    - retrying==1.3.3
    - rsa==4.6
    - scipy==1.5.4
    - semantic-version==2.8.5
    - tb-nightly==2.4.0a20201112
    - tensorboard-plugin-wit==1.7.0
    - tensorflow-estimator==2.3.0
    - tensorflow-federated-nightly==0.17.0.dev20201112
    - tensorflow-hub==0.10.0
    - tensorflow-model-optimization==0.4.1
    - tensorflow-privacy==0.5.1
    - tensorflowjs==2.7.0
    - termcolor==1.1.0
    - tf-estimator-nightly==2.4.0.dev2020102301
    - tf-nightly==2.5.0.dev20201112
    - tfa-nightly==0.12.0.dev20201110202233
    - typeguard==2.10.0
    - typing-extensions==3.7.4.3
    - urllib3==1.26.1
    - werkzeug==1.0.1
    - wrapt==1.12.1
prefix: /home/aniket/miniconda3/envs/federated
